version: '3.9'

services:
  backend:
    image: django-docker:0.0.1
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - dev-static-data:/vol/web
    env_file: /docker/.env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - es

  es:
    image: elasticsearch:8.12.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.allow-origin="*"

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file: /docker/.env
    ports:
      - "5432:5432"


volumes:
  dev-db-data:
  dev-static-data: