version: '3.9'

services:
  backend:
    image: django-docker:0.0.1
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - dev-static-data:/vol/web
    env_file: /docker/.env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_quiz_db
      - POSTGRES_USER=test_quiz_app
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"


volumes:
  dev-db-data:
  dev-static-data: